name: Grab M3U Playlist

# Jalankan manual dari tab Actions
on:
  workflow_dispatch: 

jobs:
  tarik-data:
    runs-on: ubuntu-latest
    
    # Wajib agar bot bisa upload file m3u kembali ke repositori
    permissions:
      contents: write 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Eksekusi Script PHP
      run: php ambil_m3u.php

    - name: Commit dan Push Hasil M3U ke Repo
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        git add maling.m3u
        # Perintah ini mengecek apakah ada file baru/perubahan, jika ada maka akan di-commit
        git diff --quiet && git diff --staged --quiet || git commit -m "Berhasil narik m3u terbaru"
        git push
